### PR TITLE
Update requirements to support Python 3.11 and M1 Macs

### PR DESCRIPTION
**Pull request by glennfu**
This will allow `pip install -e .` and `pytest` to succeed on an M1 Mac running Python 3.11.3. I also tested running the build on my local bot folder and clicked around a bit on the uvicorn site. I also tested importing BTC and ETH from Binance US, as well as running the example GoldenCross indicator. Everything seems to work well!

The only downside here in the requirements is that `dydx-v3-python` is tied to a [pull request](https://github.com/dydxprotocol/dydx-v3-python/pull/202) that hasn't yet been accepted. I couldn't find any way to get the requirements to build in this scenario without it.

### CODE REVIEW

**Comment by glennfu** [comment]
As an extra note, I was motivated to work on this because the current [MacOS instructions](https://docs.jesse.trade/docs/getting-started/environment-setup.html#macos) mention `numba` being optional and installing `openblas` and `scipy` instead. I followed the directions, successfully installed `openblas` and `scipy`, but my build attempts, both from `pip install jesse`, as well as building from source, didn't seem to treat `numba` as optional and would fail to build. So I found that there's a newer version of `numba` that builds successfully on my M1 Mac with Python 3.11.

**Comment by saleh-mir** [comment]
It's good news about numba. But to merge this we have to wait for DYDX PR to merge as well.

**Comment by saleh-mir** [comment]
@cryptocoinserver was there any other reason why we couldn't support python 3.10?

**Comment by glennfu** [comment]
> It's good news about numba. But to merge this we have to wait for DYDX PR to merge as well.

I wonder if we should be concerned about that. Last activity on the project was January 27th.

**Comment by movy** [comment]
Will it be merged and released any time soon? More and more issues supporting python 3.9 afloat. Update to live module are also welcome.

**Comment by saleh-mir** [comment]
I'm working on this and will included in the next release

**Comment by saleh-mir** [comment]
This is now done in the recent release. I took heavy inspiration from this pull request. Thank you for submitting it

**Pull request closed without merging**
