### PR TITLE
ARM build

### PR DESCRIPTION
**Pull request by kakulukia**
The ta-lib install script is a tiny bit out of date (last modified 2006-07-02) so this additional download enables building the docker image on ARM architecture to be able to use it on a RaspbarryPi.

### CODE REVIEW

**Comment by saleh-mir** [comment]
Hi Andy, thank you. I'm not exactly a Docker ninja, so I need some help with verifying this one. 

Did you test it on both ARM and x86 architectures to verify this change?

**Comment by kakulukia** [comment]
No, i did not test it on windows as the change is just about updating those two build files. Yes, ChatGPT did cleanup the Dockerfile and added a few comments but basically its unchanged. Make some more tests tonights - also have a windows box here.

**Comment by saleh-mir** [comment]
That would be awesome. Thank you Andy.

**Comment by kakulukia** [comment]
ERROR: jesse_live-0.48.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.

The live Plugin needs to also be compiled for the ARM platform. Can you do that?

**Comment by kakulukia** [comment]
Those build errors came from the main branch as i did not introduce code changes .. :/

**Comment by kakulukia** [comment]
=> ERROR [jesse_basic_env  7/11] RUN cd /tmp && ls -l && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*            0.2s
------
 > [jesse_basic_env  7/11] RUN cd /tmp && ls -l && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*:
0.216 total 1580
0.216 -rwxr-xr-x 1 root root    1407 May 25 09:21 install_ta-lib.sh
0.216 -rwxr-xr-x 1 root root 1330299 May 25 09:09 ta-lib-0.4.0-src.tar.gz
0.216 -rw------- 1 root root  281617 May 14 09:03 tmphrh1f073cacert.pem
0.217 /bin/sh: 1: /tmp/install_ta-lib.sh: not found
------
Dockerfile:18
--------------------
  16 |     # Install TA-lib
  17 |     COPY docker_build_helpers/* /tmp/
  18 | >>> RUN cd /tmp && ls -l && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*
  19 |     ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  20 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp && ls -l && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*" did not complete successfully: exit code: 127

This is what i get when trying to build the image on Windows, but i dont have a clue what its trying to tell me.
ls -l shows that the install script has been copied over and is set to be executable .. yet sh cant find it. 
I dont know why .. this step works just fine on OSX.

But  docker on my mac will start up an arm ubuntu which does not have a live-plugin.

This means i cant actually test this new image. :(

**Pull request closed without merging**
