### PR TITLE
Adding support for Kraken exchange

### PR DESCRIPTION
**Pull request by lightyear15**
Following patterns of other exchanges, this commit adds support for
Kraken exchange.

### CODE REVIEW

**Comment by lightyear15** [comment]
Any suggestion on how to thoroughly test it?

**Comment by saleh-mir** [comment]
Did you run it?

**Comment by lightyear15** [comment]
> Did you run it?

I ran 
```
jesse import-candles
```
and then checked database to see if values were consistent.
Any further test?

P.S. I added support for sqlite, get ready for another PR :grin:

**Comment by saleh-mir** [comment]
Hey, I appreciate your affords. 

I'm try to test it. I ran:
```
jesse import-candles Kraken BTCUSD 2020-05-25
```
And I get:
```
 Uncaught Exception: Exception: ['EQuery:Unknown asset pair']
```

> P.S. I added support for sqlite, get ready for another PR 😁
SQLite is easier to setup, but it doesn't support as much datatype as PostgreSQL. You might be able to get it working for candles now, but I'll face issues for future models. 

If you want to work on PRs, then I better create a Github project page to let you know what I need help with.

**Comment by 0xVox** [comment]
Off the top of my head; kraken ticker is XBTUSD

**Comment by saleh-mir** [comment]
@0xVox Yes that was it. How did you know? Because I checked their website and the symbol for BTC was BTC-USD, and their API doc did not provide any example

**Comment by 0xVox** [comment]
Just from memory, done some work with their API before. You can check the correct tickers with this API:

https://api.kraken.com/0/public/AssetPairs

**Comment by saleh-mir** [comment]
@lightyear15 I'm testing this. Is there a reason why set the `sleep_time` to `5` seconds? Because I read this at their docs:

> Calling the public endpoints at a frequency of 1 per second (or less) would remain within the rate limits

That means `sleep_time` of `1` would be enough.

**Comment by lightyear15** [comment]
> Hey, I appreciate your affords. 
> 
> I'm try to test it. I ran:
> ```
> jesse import-candles Kraken BTCUSD 2020-05-25
> ```
> And I get:
> ```
>  Uncaught Exception: Exception: ['EQuery:Unknown asset pair']
> ```
> 
> > P.S. I added support for sqlite, get ready for another PR 😁
> 
> SQLite is easier to setup, but it doesn't support as much datatype as PostgreSQL. You might be able to get it working for candles now, but I'll face issues for future models. 
> 
> If you want to work on PRs, then I better create a Github project page to let you know what I need help with. 

Hi,
don't ask me why, but Kraken names bitcoins XBT.
Try with xbtusd, if it doesn't work, then we have a problem. 😁

**Pull request merged**
