### PR TITLE
Bring back logging, organize imports

### PR DESCRIPTION
**Pull request by btagliani**
This outputs a csv like so:
name: `STRATEGY-Binance Perpetual Futures-BTC-USDT-1h-2023-02-01-2023-10-01.csv`
```
iteration,dna,fitness,training_log.win-rate,training_log.total,training_log.PNL,testing_log.win-rate,testing_log.total,testing_log.PNL,parameters.param,parameters.param,parameters.param,parameters.param,parameters.param
32/500,/trah,0.8070215395981797,40,22,272.94,100,2,16.44,5,10,9,11,57
32/500,"8T,1u",0.7231400310451948,57,26,199.36,25,4,-21.89,11,6,1,3,68
32/500,";J,0p",0.7202389339032377,65,26,233.92,25,4,-21.89,13,5,1,3,64
32/500,3]mZ-,0.6792009839633323,50,20,218.9,100,2,16.44,8,7,9,10,7
32/500,/an.t,0.659519247874258,33,24,180.43,100,2,16.44,5,7,9,3,67
32/500,+aV>W,0.653210871623346,26,26,180.04,100,2,21.69,2,7,6,6,43
32/500,.l^)U,0.6388706394503885,29,24,154.96,100,2,22.18,4,9,7,2,41
32/500,8en^X,0.6363064241623292,50,20,148.68,100,2,16.44,11,8,9,11,44
32/500,OK/;Z,0.6143543445551042,66,24,116.1,100,2,34.06,27,5,2,5,45
32/500,0pt<l,0.6113171478661341,36,22,131.76,100,2,21.42,6,9,10,5,61
32/500,"<I,_^",0.6052184752741345,65,26,131.6,100,2,24.6,14,5,1,11,49
32/500,40)OE,0.5624776444504851,52,36,123.25,25,4,-16.14,8,2,1,8,28
32/500,Vk6+b,0.5516369980418008,52,19,101.94,100,2,55.69,32,9,3,2,52
32/500,/`-ms,0.5329293494672593,32,28,84.47,25,4,-7.1,5,7,2,13,67
32/500,jos0c,0.5272048060929908,52,17,95.96,100,2,21.42,46,9,10,3,53
32/500,8desO,0.5262156958085725,45,20,80.95,100,2,21.59,11,8,8,14,36
32/500,:\p(-,0.5223616341003638,45,20,81.67,100,2,16.44,13,7,9,2,7
32/500,>^l3D,0.5218724029153825,50,20,79.49,100,2,16.44,15,7,9,4,27
32/500,",l21_",0.5217334078555711,25,28,74.03,25,4,-7.1,3,9,2,3,50
32/500,2_Ybg,0.514145174854318,33,24,73.16,100,2,22.18,7,7,7,12,56
32/500,;Zh+^,0.5090583392838149,50,20,78.18,100,2,21.59,13,7,8,2,49
32/500,HVSM5,0.507971264666313,55,20,64.48,100,2,21.69,22,6,6,8,14
32/500,8T1vO,0.5077633581264172,46,28,71.85,100,2,34.06,11,6,2,15,36
32/500,"wq3,r",0.499074534764125,57,19,72.36,100,2,34.06,55,9,2,3,66
32/500,/k-Ks,0.49393475896277556,32,28,58.56,25,4,-7.1,5,9,2,8,67
32/500,LWO0P,0.49116040361361074,55,20,55.67,100,2,35.45,25,6,5,3,37
32/500,5sg7`,0.49094756066137146,40,22,62.3,100,2,21.59,9,10,8,4,50
32/500,lmkTl,0.4907171654388712,58,17,70.36,100,2,16.44,47,9,9,9,61
32/500,kqnlC,0.4907171654388712,58,17,70.36,100,2,16.44,47,9,9,13,26
32/500,9/6NV,0.48484192897099304,53,28,56.4,66,3,56.42,12,2,3,8,42
32/500,/trah,0.8070215395981797,40,22,272.94,100,2,16.44,5,10,9,11,57

### CODE REVIEW

**Comment by saleh-mir** [comment]
Can you please provide a brief explanation of the functionality, possibly accompanied by an example?

**Comment by btagliani** [comment]
> Can you please provide a brief explanation of the functionality, possibly accompanied by an example?

Added to the description @saleh-mir

**Comment by saleh-mir** [comment]
Hey there! 🙌 Just wanted to say a big thank you for all the pull requests you've been sending my way. I'm definitely going to take a look at them before I roll out the next release. Keep up the great work!

**Comment by nick-dolan** [comment]
If someone looking for simple brute-force with normal (not dna) hyperparams in csv you may try my script: https://github.com/nick-dolan/brute-force-project-template

**Comment by saleh-mir** [comment]
@nick-dolan, your repository is beautifully written. Could you please submit a pull request for it at https://github.com/jesse-ai/awesome-jesse/?

I will also give it a shout out. Awesome job as always

**Comment by nick-dolan** [comment]
@saleh-mir thanks! sure!

**Pull request merged**
