### PR TITLE
docker: Switch to slim image and update python version

### PR DESCRIPTION
**Pull request by TheCrazyLex**
- Switch to slim variant of the image
-> Reduces container image size from 1.5GB to 0.9GB (40% reduction)
- Updates Python to 3.9.4

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Tested this with pytest/codecov and all tests passed.

 We could also just use the python:3.9-slim image to automatically get all new 3.9.x Python bugfix releases if you'd prefer not pinning the version.

**Comment by julesGoullee** [comment]
Hi @TheCrazyLex, can you confirm that all the dependancies install work well with the slim image, especially the compilation of ta-lib?

**Comment by TheCrazyLex** [comment]
Hi @julesGoullee, yeah all install correctly. As for the ta-lib compilation, I am pretty sure indicator tests in jesse would all fail without a properly working ta-lib present.

**Comment by julesGoullee** [comment]
mgtm

**Comment by saleh-mir** [comment]
@TheCrazyLex Thank you for submitting this.

@julesGoullee Thank you for double checking

**Pull request merged**
