### PR TITLE
add CSV Store, file export and CLI option

### PR DESCRIPTION
**Pull request by h0ke**
* add CSV Store
* add file export method
* add csv option to backtest CLI

### CODE REVIEW

**Comment by h0ke** [comment]
@saleh-mir When you get a moment, could you take a look at the data included in the CSV. I wasn't sure what you were looking to export.

Also, I attempted to match the patterns found in the codebase. Thoughts on the approach.

Thanks.

**Comment by saleh-mir** [comment]
Hey man. I appreciate your afford. I want trades that are exported as json at the end of a backtest to also be exported in CSV. Probably the easiest way is to convert json into csv. 

I read your commit. The `store` module is not meant for such use cases. It is for data that is use among different sections of the app during a session.

**Comment by h0ke** [comment]
Ah, got it. I misunderstood the TODO card. I'll change it up to convert the current json output into CSV output. If the `--csv` flag is passed in, do you still want it to output json?

**Comment by saleh-mir** [comment]
Yes, I want the json to stay there. Later I might use it for a UI

**Pull request closed without merging**
