### PR TITLE
Heikin ashi candles

### PR DESCRIPTION
**Pull request by bamartos**
Adding Heikin Ashi candles to be used as indicator on different strategies

### CODE REVIEW

**Comment by saleh-mir** [comment]
This is cool! Could you please submit a PR for the relative docs to https://github.com/jesse-ai/docs?

**Comment by saleh-mir** [comment]
Also, could you please rename `ha` to `heikin_ashi_candles`? I believe it's more convenient

**Comment by bamartos** [comment]
renaming done! I am gonna send a PR also in the docs repo!

**Comment by saleh-mir** [comment]
Thank you!

**Pull request merged**
