### PR TITLE
added a friendly version of the candles list

### PR DESCRIPTION
**Pull request by kakulukia**
image

If you also like it as much as i do, i will also build a test case and add a description for the docs.

### CODE REVIEW

**Comment by kakulukia** [comment]
The name is also up for discussion. Probably nice_candles is much easier to type.
But i certainly did not want to replace candles as this is only meant for some manual comparison rather than feeding it to indicators.

**Comment by saleh-mir** [comment]
Thank you for the pull request. But I don't think this should be in the main API because we already have properties such as self.close, self.open, self.low, self.high for the current candle. And I think that those are enough shortcuts. And if someone needs more than that, they should be okay with the default syntax for Python lists and NumPy arrays. Because they are everywhere.

**Comment by kakulukia** [comment]
I know about all the shortcuts. But yes, my picture doing a bad job for getting the original idea across as i have been using [-1]. The shortcuts work for this candle of course. But they aint working for for [-2] and so on.

**Comment by saleh-mir** [comment]
I read your code and I understand your point but I don't want to change numpy arrays a lot because they are very performant and I don't want to have a shortcut for every little thing and I'm also having an eye for future performance boost optimizations and the more classes we have the harder that's going to be but numpy arrays are already super optimized

**Comment by yakir4123** [comment]
another important thing is that ta packages prefer use np arrays and not classes

**Comment by kakulukia** [comment]
I know. That's why I did not change candles but added an additional property.

**Pull request closed without merging**
