### PR TITLE
improve visibility of entries and exits

### PR DESCRIPTION
**Pull request by macd2**

### CODE REVIEW

**Comment by cryptocoinserver** [comment]
Thank you. Can you add a screenshot of the visual changes?

**Comment by macd2** [comment]
sure here an image.
https://i.imgur.com/id9JIMM.png

1. change marker 
2. change color
3. increase size

**Comment by macd2** [comment]
@cryptocoinserver  no idea why build fails!?

**Comment by saleh-mir** [comment]
Thank you

**Comment by macd2** [comment]
> Thank you

very welcome :)

**Pull request merged**
