### PR TITLE
Fix issue #70

### PR DESCRIPTION
**Pull request by frysee**
fixes issue #70 - Optimize wont work on Windows: EOFError: Ran out of input.

### CODE REVIEW

**Comment by saleh-mir** [comment]
Hi there. Thank you for this. 

Have you tested this on platforms other than windows?

**Comment by frysee** [comment]
I can only confirm this on WIndos right now, but it should work platform independently. In any case, I should probably add a few more changes to either 
- use dill exclusively under the hood (it is an extension of pickle, the intrerface is the same) or
- make use of the `driver` config property to use either/or, which might be cleaner but needs the user to set it up correctly.

Let me know what you would prefer.

**Comment by AlphaNumeric99** [comment]
@frysee This is working quite well and not throwing error like the PyPI version. Thank you so much for this.

**Comment by saleh-mir** [comment]
I need to test this on macOS and Linux too

**Comment by reirep** [comment]
Any update on this pr ? It would be quite handy for me to be able to run the hyperopt with windows.
Thanks for the work =)

**Comment by saleh-mir** [comment]
This issue is most likely solved in the upcoming dashboard release. Because I rewrote our entire multiprocessing code in there. Thank you for the PR and sorry for my late response

**Comment by frysee** [comment]
All good, moved on to other bots anyway - good luck 👍

**Pull request closed without merging**
