### PR TITLE
Adding if cases for EUR in helpers functions

### PR DESCRIPTION
**Pull request by lightyear15**
In functions base_asset and quote_asset there are special if cases for
USDT and USD, this commit refactors the functions to accept easily any
other special cases like EUR GBP or BNB.

### CODE REVIEW

**Comment by lightyear15** [comment]
I am not sure how,
but apparently the build or the CI pipeline are broken.
No?

**Comment by saleh-mir** [comment]
I don't know why I missed the email notification for this. This is great. But please add proper changes to their unit tests as well. Thank you

**Comment by lightyear15** [comment]
Unit tests updated.
Let me know if you want me to add more symbols to the list...
``USDC``, ``AUD``, ...

**Comment by saleh-mir** [comment]
Thank you. But I gotta mention that we have a branch under dev to completely change how we handle these. After that, we'll be using symbols as `BTC-USD` instead which makes it easier to support all pairs.

**Pull request merged**
