### PR TITLE
tool for showing candle DB overview

### PR DESCRIPTION
**Pull request by poe28**

### CODE REVIEW

**Comment by saleh-mir** [comment]
Can you please explain what this tool does and how is it useful?

**Comment by tillmo** [comment]
The tool gives a quick overview of the candles stored in the database. For the sake of speed, it uses postgres directly, but if more appropriate, it could also be done using the Python interface, of course. A typical outcome is:
```
$ utils/candle_info.sh jesse_db
  min_date  |  max_date  |  count  |  symbol  |  exchange   
------------+------------+---------+----------+-------------
 2017-10-01 | 2021-11-18 | 2174224 | BTC-EUR  | Bitfinex
 2017-01-01 | 2021-11-20 | 2569897 | ETH-BTC  | Bitfinex
 2018-06-01 | 2021-11-20 | 1827011 | ETH-EUR  | Bitfinex
 2017-10-01 | 2021-11-10 | 2133780 | BTC-EUR  | Coinbase
 2017-01-02 | 2021-11-20 | 2428540 | ETH-BTC  | Coinbase
 2018-06-01 | 2021-11-17 | 1788565 | ETH-EUR  | Coinbase
 2019-10-24 | 2021-12-12 | 1123698 | ADA-USD  | FTX Futures
 2020-09-23 | 2021-11-20 |  610254 | AVAX-USD | FTX Futures
 2019-07-21 | 2021-11-18 | 1226493 | BTC-PERP | FTX Futures
 2019-07-21 | 2021-12-11 | 1259865 | BTC-USD  | FTX Futures
 2019-07-21 | 2021-11-18 | 1226702 | ETH-PERP | FTX Futures
 2019-07-21 | 2021-12-11 | 1259867 | ETH-USD  | FTX Futures
 2021-11-20 | 2021-11-21 |    2027 | GALA-USD | FTX Futures
 2020-07-28 | 2021-11-20 |  692315 | SOL-USD  | FTX Futures
(14 lines)
```

**Comment by poe28** [comment]
The tool gives a quick overview of the candles stored in the database. For the sake of speed, it uses postgres directly, but if more appropriate, it could also be done using the Python interface, of course. A typical outcome is:
```
$ utils/candle_info.sh jesse_db
  min_date  |  max_date  |  count  |  symbol  |  exchange   
------------+------------+---------+----------+-------------
 2017-10-01 | 2021-11-18 | 2174224 | BTC-EUR  | Bitfinex
 2017-01-01 | 2021-11-20 | 2569897 | ETH-BTC  | Bitfinex
 2018-06-01 | 2021-11-20 | 1827011 | ETH-EUR  | Bitfinex
 2017-10-01 | 2021-11-10 | 2133780 | BTC-EUR  | Coinbase
 2017-01-02 | 2021-11-20 | 2428540 | ETH-BTC  | Coinbase
 2018-06-01 | 2021-11-17 | 1788565 | ETH-EUR  | Coinbase
 2019-10-24 | 2021-12-12 | 1123698 | ADA-USD  | FTX Futures
 2020-09-23 | 2021-11-20 |  610254 | AVAX-USD | FTX Futures
 2019-07-21 | 2021-11-18 | 1226493 | BTC-PERP | FTX Futures
 2019-07-21 | 2021-12-11 | 1259865 | BTC-USD  | FTX Futures
 2019-07-21 | 2021-11-18 | 1226702 | ETH-PERP | FTX Futures
 2019-07-21 | 2021-12-11 | 1259867 | ETH-USD  | FTX Futures
 2021-11-20 | 2021-11-21 |    2027 | GALA-USD | FTX Futures
 2020-07-28 | 2021-11-20 |  692315 | SOL-USD  | FTX Futures
(14 lines)
```

**Comment by fabegreat** [comment]
+1 for this feature

**Comment by saleh-mir** [comment]
This is pretty useful. Thank you!

**Comment by fabegreat** [comment]
In case helpful, I've used this query to get such a table: select to_timestamp(min(timestamp)/1000)::date as from,to_timestamp(max(timestamp)/1000)::date as to, count(symbol) as count, symbol,exchange from candle group by exchange,symbol;

**Comment by saleh-mir** [comment]
Having this as a file in the main framework is not really useful to most users because they cannot run it (not everyone installs Jesse via the source code). Would be great if we could run this via Python and convert the result into `dict`, `list`, or something. Then I'd be able to display it as a table in the dashboard which makes it accessible to everybody.

**Comment by fabegreat** [comment]
Jupyter notebook script:
#import library psycopyg2 and sqlio
import psycopg2
import pandas.io.sql as sqlio

#create database connection variable 
conn = psycopg2.connect(user="jesse_user", password="", host="localhost", database="jesse_db")

#define query
query = "select to_timestamp(min(timestamp)/1000)::date as from,to_timestamp(max(timestamp)/1000)::date " \
        "as to, count(symbol) as count, symbol,exchange from candle group by exchange,symbol;"

print(sqlio.read_sql_query(query,conn))

**Pull request merged**
