### PR TITLE
adding additional parameters to srsi indicator (leaving same defaults)

### PR DESCRIPTION
**Pull request by Gabri**

### CODE REVIEW

**Comment by saleh-mir** [comment]
Thank you. I think it's a good PR since tradingview has these parameters for SRSI too but I find the names confusing. I want to keep the parameter names the same as tradingview:

Screen Shot 2020-06-15 at 12 05 20 PM

**Comment by Gabri** [comment]
I absolutely agree

**Comment by Gabri** [comment]
I leaved the main parameter name as `period` (RSI Length) because it is the default name in other indicators, I put a specification on comment.
I think the build error is not about my changes, has failed during the ta-lib library download:
`wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -q`
I haven't found a way to start a new build manually (I could make a dummy commit eventually..)

**Comment by saleh-mir** [comment]
thank you

**Pull request merged**
