### PR TITLE
added elitism to genetic/evolution algorithm

### PR DESCRIPTION
**Pull request by gister9000**
I let optimize mode overnight and woke up to see worse DNAs than when I left off. We should always keep the best DNA alive to prevent this from happening. Also, we should never keep more than 1 alive because that will kill the population diversity. I plan to make further improvements one by one in order to keep things under control and each change is evaluated individually.

### CODE REVIEW

**Comment by gister9000** [comment]
Too many backtests are done on shitty dna so I lowered population size. First phase will also be 5x smaller. The cost again is diversity. I am running comparison tests now (will run each config many times before drawing conclusions). If diversity is an issue we can increase the population size again a little.

**Comment by gister9000** [comment]
`~/PycharmProjects/fork/jesse$ pytest
========================================== test session starts ==========================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.0
rootdir: /home/prase/PycharmProjects/fork/jesse
collected 307 items                                                                                     

tests/test_backtest.py ..                                                                         [  0%]
tests/test_broker.py ......                                                                       [  2%]
tests/test_candle_service.py .....                                                                [  4%]
tests/test_conflicting_orders.py ...                                                              [  5%]
tests/test_helpers.py ...................................................................         [ 27%]
tests/test_import_candles.py ...                                                                  [ 28%]
tests/test_indicators.py ........................................................................ [ 51%]
.....................................................                                             [ 68%]
tests/test_metrics.py .                                                                           [ 69%]
tests/test_order.py ..                                                                            [ 69%]
tests/test_parent_strategy.py ........................................                            [ 82%]
tests/test_position.py ..............                                                             [ 87%]
tests/test_router.py .                                                                            [ 87%]
tests/test_state_candle.py .....                                                                  [ 89%]
tests/test_state_exchanges.py .                                                                   [ 89%]
tests/test_state_logs.py ..                                                                       [ 90%]
tests/test_state_orderbook.py ...                                                                 [ 91%]
tests/test_state_orders.py .....                                                                  [ 92%]
tests/test_state_ticker.py ..                                                                     [ 93%]
tests/test_state_trades.py .                                                                      [ 93%]
tests/test_trade.py ........                                                                      [ 96%]
tests/test_utils.py ...........                                                                   [100%]

========================================== 307 passed in 7.91s ==========================================
`

**Comment by saleh-mir** [comment]
Hey, thanks for this. I'll merge the first part about the elitism but not the sone about lowering the population_size. I'd have to try that by myself. The current number was working fine for me. In fact I'm going to use the optimize mode a lot in the coming days, so I'll see about that.

**Comment by gister9000** [comment]
Definitely test increasing selective pressure as long as enough diversity is preserved. There is definitely a sweet are where algo almost never gets stuck with many almost identical dnas, but still find good samples fast

**Comment by saleh-mir** [comment]
Thank you

**Pull request merged**
